django_testing_examples/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
]

myapp/urls.py
from django.conf.urls import url
from rest_framework import renderers
from django.urls import path, include
from . import views

rental_list = views.RentalViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
rental_detail = views.RentalViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})


reservation_list = views.ReservationViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
reservation_detail = views.ReservationViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})



app_name = 'myapp'
urlpatterns = [
    url(r'^createreservation/', views.ReservationView.as_view(), name='myview'),
    url(r'^createrental/', views.RentalView.as_view(), name='myview2'),
    url(r'^create/$', views.RentalView.as_view(), name='mycreateview'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.ReservationView.as_view(), name='myupdateview'),
    path('rentals/', rental_list, name='rental-list'),
    path('rentals/<int:pk>/', rental_detail, name='rental-detail'),
    path('reservations/', reservation_list, name='reservation-list'),
    path('reservations/<int:pk>/', reservation_detail, name='reservation-detail'),


]

myapp/models.py
from django.db import models

class Rental(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(unique=True)

class Reservation(models.Model):
    id = models.AutoField(primary_key=True)
    rental_id = models.ForeignKey(Rental,on_delete=models.CASCADE)
    rental_name = models.TextField()
    name = models.TextField(null=True)
    checkin_date = models.DateField(auto_now=False, auto_now_add=False)
    checkout_date = models.DateField(auto_now=False, auto_now_add=False)
    previous_reservation = models.TextField(null=True)

myapp/forms.py
from django import forms

from myapp.models import Reservation,Rental

class DateInput(forms.DateInput):
    input_type = 'date'

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['rental_name','checkin_date','checkout_date']
        widgets = {
          'rental_name': forms.Textarea(attrs={'rows':1, 'cols':40}),
          'checkin_date':  DateInput(),
          'checkout_date':  DateInput()
        }


class RentalForm(forms.ModelForm):
    class Meta:
        model = Rental
        fields = ['name']
        widgets = {
          'name': forms.Textarea(attrs={'rows':1, 'cols':40}),
        }

myapp/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.views import generic, View
from rest_framework import viewsets
from rest_framework import permissions
from myapp.serializers import RentalSerializer,ReservationSerializer
from myapp import models, forms
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import renderers
from rest_framework.exceptions import APIException
from datetime import datetime,timedelta
import requests
from django.urls import resolve


class ReservationView(View):
    model = models.Reservation
    form_class = forms.ReservationForm
    def get(self, request, *args, **kwargs):
        form = forms.ReservationForm()
        context = {'form': form}
        return render(request, 'myapp/reservation.html', context)

class RentalView(View):
    model = models.Rental
    form_class = forms.RentalForm
    def get(self, request, *args, **kwargs):
        form = forms.RentalForm()
        context = {'form': form}
        return render(request, 'myapp/rental.html', context)


class UpdateReservationView(generic.UpdateView):
    model = models.Reservation
    form_class = forms.ReservationForm
    success_url = "/update_success/"

class CreateReservation(generic.CreateView):
    model = models.Reservation
    form_class = forms.ReservationForm
    success_url = "/create_success/"

class CreateRental(generic.CreateView):
    model = models.Rental
    form_class = forms.RentalForm
    success_url = "/create_success/"


class RentalViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows rentals to be viewed or created.
    """
    queryset = models.Rental.objects.all()
    serializer_class = RentalSerializer

    def perform_create(self, serializer):
        serializer.save()

class ReservationViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows reservations to be viewed or created.
    """
    queryset = models.Reservation.objects.all()
    serializer_class = ReservationSerializer

    def perform_create(self, serializer):
        try:
            checkin_date = self.request.POST.get('checkin_date')
            checkout_date = self.request.POST.get('checkout_date')
            rental_name = self.request.POST.get('rental_name')
        except Exception as e:
            raise APIException('Error getting POST variables ' + str(self.request.POST))
        try:
            rental_id = models.Rental.objects.get(name=rental_name)
            if rental_id is None:
                r = Rental(name=rental_name)
                r.save()
                rental_id = r
                #raise APIException("Rental does not exist!")

            if checkin_date > checkout_date:
                raise APIException("Check-in is after checkout!")
            
            objects = models.Reservation.objects.filter(rental_id=rental_id)
            previous_reservation = None
            if len(objects) > 0:
                previous_reservation = objects
                overlapping_reservation_checkin = objects.filter(checkin_date__range=[checkin_date ,checkout_date])
                if overlapping_reservation_checkin:
                    raise APIException("There is an overlapping reservation")
                overlapping_reservation_checkout = objects.filter(checkout_date__range=[checkin_date ,checkout_date])
                if overlapping_reservation_checkout:
                    raise APIException("There is an overlapping reservation")
                if checkin_date==checkout_date:
                    overlapping_reservation_checkout = objects.filter(checkout_date__range=[checkin_date ,checkin_date])
                    if overlapping_reservation_checkout:
                        raise APIException("There is an overlapping reservation")
                previous_reservation= previous_reservation.order_by('-id')[0]
                previous_reservation = 'Res-' + str(previous_reservation.id)

                    
                
            current_obj = serializer.save(rental_id=rental_id,previous_reservation=previous_reservation)
            current_obj.name = 'Res-' + str(current_obj.id)
            current_obj.save()

        except Exception as e:
            print(e)
            raise APIException(e)
        

myapp/templates/myapp/rental.html
<head>
    <title>Rental</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"> {% block extra_head %} {% endblock %}
</head>

<body>
    <a href='/createreservation'>Reservation</a><br/><br/>
    <h1>Rental</h1>
    <div class="container mt-5">
        {% block content %}
        <div class="column is-one-third">
            <form action='#'>
                {% csrf_token %} {{ form.as_p }}
            </form>
            <button onclick="submit_data()" class="button is-success is-fullwidth is-medium mt-5">Create Rental</button>
        </div>

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <table id="myStaticDatatable">
        <thead>
            <tr>
                <th>Rental Name</th>
            </tr>
        </thead>
    </table>
    <script>
    </script>

    {% block extra_js %}
    <script>
        var table;
        let data_url = '/rentals?format=datatables';
        $(document).ready(function() {
            table = $('#myStaticDatatable').DataTable({
                'order': [
                    [0, 'asc']
                ],
                'processing': true,
                'serverSide': false,
                'ajax': {
                    url: data_url,
                    dataSrc: 'data'
                },
                columns: [

                    {
                        data: 'name',
                        orderable: true
                    },

                ]
            });
        });

        function submit_data() {
            var name = $('#id_name').val();
            console.log(name);
            $.ajax({
                type: "POST",
                url: '/rentals/',
                dataType: "json",
                data: {
                    "name": name
                },
                success: function(response) {
                    //if request if made successfully then the response represent the data
                    alert('Rental successfully added');
                    table.ajax.reload();

                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Error: " + errorThrown);
                }
            });
        }
    </script>
    {% endblock %}
</body>

myapp/templates/myapp/reservation.html
<head>
    <title>DataTable</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"> {% block extra_head %} {% endblock %}
</head>

<body>
    <a href='/createrental'>Rental</a> (You have to create a rental before reservation) <br/><br/>
    <h1>Reservation</h1>
    <div class="container mt-5">
        {% block content %}
        <div class="column is-one-third">
            <form action="#">
                {% csrf_token %} {{ form.as_p }}

            </form>
            <button class="button is-success is-fullwidth is-medium mt-5" onclick="submit_data()">Create reservation
            </button>

        </div>

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <table id="myStaticDatatable">
        <thead>
            <tr>
                <th>Reservation ID</th>
                <th>Reservation Name</th>
                <th>Rental Name</th>
                <th>Check-in Date</th>
                <th>Check-out Date</th>
                <th>Previous Reservation</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>


    {% block extra_js %}
    <script>
        var table;
        let data_url = '/reservations?format=datatables';
        $(document).ready(function() {
            table = $('#myStaticDatatable').DataTable({
                'order': [
                    [0, 'asc']
                ],
                'processing': true,
                'serverSide': false,
                'ajax': {
                    url: data_url,
                    dataSrc: 'data'
                },
                columns: [{
                        data: 'id',
                        orderable: true
                    }, {
                        data: 'name',
                        orderable: true
                    }, {
                        data: 'rental_name',
                        orderable: true
                    }, {
                        data: 'checkin_date',
                        orderable: true
                    }, {
                        data: 'checkout_date',
                        orderable: true
                    }, {
                        data: 'previous_reservation',
                        orderable: true
                    }

                ]
            });
        });

        function submit_data() {
            var name = $('#id_name').val();
            var rental_name = $('#id_rental_name').val();
            var checkin_date = $('#id_checkin_date').val();
            var checkout_date = $('#id_checkout_date').val();
            $.ajax({
                type: "POST",
                url: '/reservations/',
                dataType: "json",
                data: {
                    "rental_name": rental_name,
                    "checkin_date": checkin_date,
                    "checkout_date": checkout_date
                },
                success: function(response) {
                    //if request if made successfully then the response represent the data
                    alert('Reservation successfully added');
                    table.ajax.reload();

                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    alert("Error: " + JSON.parse(XMLHttpRequest.responseText)['detail']);
                }
            });
        }
    </script>
    {% endblock %}
</body>